import {LOGIN_FORM_FIELD_KEY} from './frame/login-form/login-form.constants'

export const LOGIN_FIELD_NAME = {
  LOGIN: 'login',
  PASSWORD: 'password'
};

export const LOGIN_FORM_FIELD_NAME = {
  [LOGIN_FORM_FIELD_KEY.LOGIN]: 'login',
  [LOGIN_FORM_FIELD_KEY.PASSWORD]: 'password'
};

export const LOGIN_ACTION_TYPE = {
  LOGIN_FORM_UPLOAD_PENDING: 'LOGIN_ACTION_TYPE.LOGIN_FORM_UPLOAD_PENDING',
  LOGIN_FORM_UPLOAD_SUCCESS: 'LOGIN_ACTION_TYPE.LOGIN_FORM_UPLOAD_SUCCESS',
  LOGIN_FORM_UPLOAD_ERROR: 'LOGIN_ACTION_TYPE.LOGIN_FORM_UPLOAD_ERROR',
  // LOGIN_FORM_UPLOAD_RESET: 'LOGIN_ACTION_TYPE.LOGIN_FORM_UPLOAD_RESET',
};

export const LOGIN_DATA_NAME = {
  LOGIN: 'login',
  PASSWORD: 'password'
};